### ISSUE TITLE
What is the status of the code supporting these webcams?

### ISSUE THREAD

**Issue by caio1982** [patjak/bcwc_pcie#10]
Hi there! I just wanted to thank you for your effort and thanks to a recent Hacker News post I decided to stop by not to bug you but to actually ask (quite generally speaking) what is the current status of the work?

Just to be clear, I am not demanding anything, I am simply curious because there is some activity going on but it's hard to tell what's up from the outside :-)

**Comment by patjak** [comment]
Hi Caio
I'm currently busy with other things but I'm still working on the driver. I'll be pushing code and reporting anything of interest to this github project.

Cheers

**Comment by kitt3n** [comment]
Awesome! There's a 50 dollar bounty on bountysource by me claimable when the driver's functional enough for use, hence the "issue" by me on the project.

**Comment by kie27** [comment]
For anyone else wishing to add to the bounty, the URL is https://www.bountysource.com/teams/bcwc_pcie
I can also add this to the wikipedia entry.

**Comment by kitt3n** [comment]
That would be amazing! :D

**Comment by 0xbb** [comment]
I also added 25 dollar to the bounty.

**Comment by danmilon** [comment]
Also added $15.

**Comment by kie27** [comment]
I have also added $10.

**Comment by pquentin** [comment]
Added 25$.

**Comment by kie27** [comment]
I have added this to the wiki.

**Comment by patjak** [comment]
Wow, that was quick. Thanks for the help. Hopefully this will bring in more people interested in development as well.

**Comment by rodrigoaguilera** [comment]
http://i1290.photobucket.com/albums/b530/Rhinosus13/meme-well-that-escalated-quickly_zps70fb859c.jpg

**Comment by Se6** [comment]
Hi,

Can't contribute to the Bounty any more it seems. It says "Note: Donations are disabled because this team has no members."

**Comment by kitt3n** [comment]
https://www.bountysource.com/issues/7700750-basic-functionality On this page, you can "post a bounty" to increase the bounty. :)

**Comment by zimbatm** [comment]
[![Bountysource](https://www.bountysource.com/badge/team?team_id=50420&style=bounties_received)](https://www.bountysource.com/teams/bcwc_pcie/issues?utm_source=bcwc_pcie&utm_medium=shield&utm_campaign=bounties_received)

**Comment by mrjesseolsson** [comment]
@patjak I can't add to the bounty but this would be super awesome and I hope you get it working :)

**Comment by JacobMillward** [comment]
I'd love to help with this, where do I get started?

**Comment by patjak** [comment]
Hi @JacobMillward
It depends on how much you know about reverse engineering. I've set up an IRC channel on freenode for discussion: #bcwc_pcie

**Comment by JacobMillward** [comment]
@patjak I'll be hanging out on the IRC for a while, and whenever I have some free time.

**Comment by christianbundy** [comment]
@patjak I believe this issue is ready to be closed now that we have #9
