### ISSUE TITLE
not working with ubuntu 16.10

### ISSUE THREAD

**Issue by pacuna** [patjak/bcwc_pcie#106]
Is this because of my kernel version? I saw there's a known issue with kernels later than 4.5

```
$ uname -r
4.8.0-32-generic
```

**Comment by patjak** [comment]
afaik it should work on 16.10. Can you describe your problem in more detail?

**Comment by pacuna** [comment]
@patjak I followed all of the instructions and everything went OK but I sill get no device found (I tried the installation 2 times and rebooting after). Is there any command I can run to show you more information?

**Comment by patjak** [comment]
Did you take a look at the "Known issues" section in the wiki? You might have missed to unload the bdc_pcie module.

**Comment by pacuna** [comment]
thanks @patjak ! That did the work.
