### ISSUE TITLE
Wrong white balance

### ISSUE THREAD

**Issue by scottmangiapane** [patjak/bcwc_pcie#109]
I'm running Ubuntu 16.10 on the Macbook Pro 15" from mid-2015. For some reason, the webcam doesn't always display the correct white balance when using this driver. It works fine during the day in sunlight, but at night when I use artificial lighting everything has an orange tint. I've confirmed that auto-white-balance is enabled for the driver, yet the image still looks off.

Any support would be appreciated :)

**Comment by patjak** [comment]
Marking this as a duplicate of issue #96 
Please reopen if you think it's incorrect.
