### ISSUE TITLE
Wiki needs updating

### ISSUE THREAD

**Issue by Stono** [patjak/bcwc_pcie#110]
Hey,
Your wiki on https://github.com/patjak/bcwc_pcie/wiki says "The driver will not compile for 4.5 and later kernels. Will fix this up when we're in good enough shape for mainlining.", this isn't true as I'm on `4.9.11-200.fc25.x86_64`, so probably want to update that.

I use the following gist to handle recompilation each time update my kernel too.
https://gist.github.com/Stono/990ea9f0b3c41606c292f00382d421bf

PS. Thanks :-) Nice having my webcam working in Linux

**Comment by patjak** [comment]
Updated wiki, thanks.
