### ISSUE TITLE
ELEMENTARY 

### ISSUE THREAD

**Issue by pierre-weiss** [patjak/bcwc_pcie#111]
Just a small comment to say that the driver seems to be working for Elementary OS. You just need to follow the steps for Ubuntu. At the end of the installation, I had to type
depmod -a
sudo modprobe facetimehd
and it seems to be running smoothly.

Note : 
dmesg still gives the known issue :
[ 4477.285182] facetimehd 0000:02:00.0: firmware: facetimehd/1871_01XX.dat will not be loaded

**Comment by derjohn** [comment]
Hello,
is this an issue or an success report? :)

The error "Direct firmware load for facetimehd/1871_01XX.dat failed with error -2" is harmless.

I just wonder, why you didn't need to sudo  before "depmod -a" ..

rgds,
j

**Comment by pierre-weiss** [comment]
This is a success :). I first wrote an issue, then double checked the
threads and remarked it was in fact working after adding the depmod
commands. All was done after sudo su, so that I forgot adding it in my
thread.

I wanted to change the title or even discard the issue, but I couldn't...

My main intention was to advertise that Elementary OS could be done
following the guidelines for Ubuntu + the depmod commands...

Thanks for the hard work,
Very best regards,
Pierre Weiss


2017-04-13 8:56 GMT+02:00 derjohn <notifications@github.com>:

**Comment by patjak** [comment]
Thanks for letting us know. Closing.
