### ISSUE TITLE
The driver hangs Open Broadcaster Software and the module gets subsequently frozen

### ISSUE THREAD

**Issue by arun-gurung** [patjak/bcwc_pcie#124]
After an hour or so, OBS will hang and when I restart it, the module has frozen and no webcam software will recognise the facetimehd. I cannot unload and reload the module.

My other camera, Logitech HD Pro Webcam C920 still works good in OBS and it will not hang OBS.

**Comment by patjak** [comment]
Can you see anything suspicious in dmesg when this happen?

**Comment by arun-gurung** [comment]
The only abnormality in dmesg is this and I don't know if it tells anything:

Jun 20 20:15:23 macbook-air kernel: facetimehd 0000:02:00.0: IO: timeout

**Comment by arun-gurung** [comment]
I'm sorry, but now OBS hangs also when only using my Logitech C920 and not only the facetimehd camera. But I don't get if this is an internal fault in OBS, because the facetimehd module hangs and not the Logitech.

**Comment by arun-gurung** [comment]
This is very weird: Now my facetimehd suddenly works in OBS without reloading the module, but the Logitech C920 has blacked out in OBS. But the C920 works in the "guvcview" webcam program.

**Comment by arun-gurung** [comment]
Now OBS hanged after thirty minutes. I "xkill" it and restarted as soon as possible and the two cameras were still available to resume the stream.

**Comment by patjak** [comment]
It sounds like a bug in OBS to me. There still might be a problem in facetimehd for handling misbehaving v4l2 clients. I'll experiment some with OBS on my own and see if I run into the same issue.

**Comment by arun-gurung** [comment]
Yes, it looke like a bug in OBS. Mind you, the facetimehd stopped in OBS and came back the second time I started OBS.

**Comment by arun-gurung** [comment]
It must definitely be a problem with OBS. I use Guvcview webcam software and both cameras now work here without me rebooting the system.

**Comment by arun-gurung** [comment]
Yes, there must be an error with OBS, because I now restarted OBS and both facetimehd and Logitech C920 still works.

After 30 minutes to only an hour, the OBS will freeze, but the video still is streaming but I can´t do any changes in OBS after this.

**Comment by arun-gurung** [comment]
Even if OBS has a bug, there still the frozen facetimehd module it leaves behind. So there must also be an error in facetimehd since I am unable to unload/reload it.

**Comment by arun-gurung** [comment]
I now have Linux 4.18 and OBS 24.0.1 and the problem is gone.

**Comment by patjak** [comment]
Perhaps this got solved by 9190f7d3b8e26179149a90b3d0138e6bc179afab
Thanks for testing
