### ISSUE TITLE
Make it working on reboot

### ISSUE THREAD

**Issue by marabesi** [patjak/bcwc_pcie#128]
Hello guys, I' ve got the camera working on my macbook pro using this repo, but everything that I reboot I need to run 

```
   sudo modprobe -r bdc_pci
   sudo lsmod| grep face
   sudo depmod
   sudo modprobe facetimehd
   sudo lsmod| grep face

```

Is there a way to make it last even when I reboot?

obs: I am running ubuntu 16.04

Thanks

**Comment by hobarrera** [comment]
Yes, that's documented in [the wiki](https://github.com/patjak/bcwc_pcie/wiki/Get-Started#make-driver-load-correctly-on-startupi:

```bash
echo facetimehd >> /etc/modules   # Note: run this as root.
```

**Comment by marabesi** [comment]
That's correct, I am going to close the issue as the problem is well documented.

Thanks
