### ISSUE TITLE
Module refuses to load on latest Arch kernel (4.12.12-1-ARCH)

### ISSUE THREAD

**Issue by slashrsm** [patjak/bcwc_pcie#138]
When I try to load the module I get the following message:

```
➜  sudo modprobe facetimehd
modprobe: ERROR: could not insert 'facetimehd': Exec format error
```

There is also an error in dmesg:

`
[  577.828988] facetimehd: disagrees about version of symbol module_layout
`

Any idea how to fix this?

**Comment by hobarrera** [comment]
Did you install it via DKMS? If you didn't you probably need to manually rebuild the module.

**Comment by slashrsm** [comment]
I did. Actually, I tried DKMS and manually rebuilding. Same result.

**Comment by hobarrera** [comment]
That's odd. Arch user (and the downstream package maintainer too) here, and the module has worked on recent arch kernels (currently 4.13.2-1).

Can you check if 4.13.2-1 give the same error?

**Comment by slashrsm** [comment]
Today my system updated to 4.13.3-1 and auto-resolved the problem. Thanks!
