### ISSUE TITLE
Doesn't run after restarting computer

### ISSUE THREAD

**Issue by agil17** [patjak/bcwc_pcie#177]
After running the script, the camera works, and it's great, but after shutting down my cpu and restarting it, it no longer works and have to redo it. Is it possible to make it a personal solution?

**Comment by hdoupe** [comment]
This happened to me, too. Does anyone have any advice for dealing with this?

**Comment by hdoupe** [comment]
This is resolved in #51. Check out the docs here: https://github.com/patjak/bcwc_pcie/wiki/Get-Started#make-driver-load-correctly-after-suspend
