### ISSUE TITLE
Ubuntu (kernel?) confused:  ‘-mindirect-branch’ and ‘-fcf-protection’ are not compatible

### ISSUE THREAD

**Issue by YannChemin** [patjak/bcwc_pcie#185]
Making from Master branch.
Many similar issues appearing, this is last one.

> bcwc_pcie/fthd_ddr.c:631:1: error: ‘-mindirect-branch’ and ‘-fcf-protection’ are not compatible

**Comment by patjak** [comment]
I think this is a distro/compiler issue and not a bug in the driver.
Perhaps this link helps: https://bugs.launchpad.net/ubuntu/+source/gcc-9/+bug/1830961
