### ISSUE TITLE
low resolution (320x240) by default

### ISSUE THREAD

**Issue by toaster** [patjak/bcwc_pcie#19]
I got the driver working under Gentoo with kernel 4.3.3 and Firmware 1.43.0. The resolution is low by default and the only way to get a higher one is via `mplayer tv:// -tv width=1280:height=720`.

Especially Google hangouts do not use the high resolution.

**Comment by arnal88** [comment]
I got the same problem with Skype (low resolution 320x240 by default)!
It seems that some applications such as Skype or Google Hangouts use the lowest available resolution by default. I managed to overcome this issue by increasing the minimum resolution of the webcam `facetimehd` module.
See #52

**Comment by patjak** [comment]
Not sure we should cripple the capabilities to fix broken applications. Will check how other drivers handle this. I'll keep the https://github.com/patjak/bcwc_pcie/issues/52 issue open for now if someone else needs to use the workaround.
