### ISSUE TITLE
doesn't assemble on kernel 5.2.21-1-MANJARO 

### ISSUE THREAD

**Issue by GusevAG** [patjak/bcwc_pcie#190]
I've tried to install the https://aur.archlinux.org/packages/bcwc-pcie-git/ 
and this is the error I got 
`Updating linux52 module dependencies...
Install DKMS modules
Arming ConditionNeedsUpdate...
Updating the info directory file...

Building facetimehd-firmware...
==> Making package: facetimehd-firmware 1.43.0-1 (Птн 25 окт 2019 16:13:22)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning facetimehd-firmware git repo...
Cloning into bare repository '/var/tmp/pamac-build-andrey/facetimehd-firmware/facetimehd-firmware'...
==> Validating source files with md5sums...
    facetimehd-firmware ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of facetimehd-firmware git repo...
Cloning into 'facetimehd-firmware'...
done.
==> Starting prepare()...

Checking dependencies for driver download...
/usr/bin/curl
/usr/bin/xzcat
/usr/bin/cpio

Downloading the driver, please wait...
mv: cannot stat 'System/Library/Extensions/AppleCameraInterface.kext/Contents/MacOS/AppleCameraInterface': No such file or directory
make: *** [Makefile:41: AppleCameraInterface] Error 1
==> ERROR: A failure occurred in prepare().
    Aborting...
`
it seems that the facetimehd-firmware is not adapted to 5.2 kernel 
please fix it if possible

**Comment by patjak** [comment]
@offlinehacker 's fix is now available in https://github.com/patjak/facetimehd-firmware
