### ISSUE TITLE
skype desktop black window

### ISSUE THREAD

**Issue by drinkingcoffee** [patjak/bcwc_pcie#214]
Has anyone had any luck with the skype for linux desktop?

I am able to use skype through the web interface in chrome, but that has its own issues. The desktop version just gives me a black window for my webcam video. 
Thanks.

**Comment by gabriel-lucas** [comment]
Just to let you know that you are not alone.
No idea about the state of this but there seems to be relevant information here.
 https://github.com/patjak/bcwc_pcie/issues/123

**Comment by patjak** [comment]
See fix in #123
