### ISSUE TITLE
ioremap_nocache() has been killed, needs changing to ioremap()

### ISSUE THREAD

**Issue by HaydnH** [patjak/bcwc_pcie#220]
Hi Guys,

As per the below RFC, ioremap_nocache() has been killed off and should be replaced with ioremap() or this fails to build on newer kernels:

https://lore.kernel.org/linux-mips/20191209194819.GA28157@lst.de/T/

There are only 3 instances to change:

```
# diff fthd_drv.c.OLD fthd_drv.c
73c73
< 	dev_priv->s2_io = ioremap_nocache(start, len);
---
> 	dev_priv->s2_io = ioremap(start, len);
79c79
< 	dev_priv->s2_mem = ioremap_nocache(start, len);
---
> 	dev_priv->s2_mem = ioremap(start, len);
85c85
< 	dev_priv->isp_io = ioremap_nocache(start, len);
---
> 	dev_priv->isp_io = ioremap(start, len);

```

Regards,

Haydn.

**Comment by patjak** [comment]
Hi, this is already fixed in e989703071246a9d4e6d75e8de34b746b707ecde
