### ISSUE TITLE
Unable to get Apple thunderbolt display webcam working

### ISSUE THREAD

**Issue by bsbretly** [patjak/bcwc_pcie#232]
Hello,

I am currently having issues getting the webcam on my Apple thunderbolt display to be detected. My setup is as follows:

Software: Ubuntu 20.04 with kernel 5.4.0-52-generic.

Hardware: Lenovo X1 carbon gen 7, Apple thunderbolt 3 to thunderbolt 2 adapter, Apple thunderbolt display(with webcam)

Upon booting up my laptop with my Apple display connected, I am only able to see my laptop's integrated webcam but not the webcam from my external display. The terminal command `v4l2-ctl --list-devices` outputs:
```
Integrated Camera: Integrated C (usb-0000:00:14.0-8):
	/dev/video0
	/dev/video1
```

I've extracted and installed the facetimehd driver without issues/errors, though still am not seeing the webcam in my /dev/video* directory (I only see my integrated webcam here). I've followed some of the potential fixed from this thread: https://github.com/patjak/bcwc_pcie/issues/49, though my issue persists. 

If I physically disconnect/reconnect my thunderbolt 3 from my laptop, however, and repeat the command `v4l2-ctl --list-devices`, I see the output:

```
Integrated Camera: Integrated C (usb-0000:00:14.0-8):
	/dev/video0
	/dev/video1

FaceTime HD Camera (Display): F (usb-0000:32:00.2-1.5):
	/dev/video2
	/dev/video3
```

So, my Apple display webcam is now detected and functions with apps such as Skype. I've taken a look at what driver each webcam is using via the command `ls -ld /sys/class/video4linux/video0/device/driver`:
```
lrwxrwxrwx 1 root root 0 Oct 31 21:10 /sys/class/video4linux/video1/device/driver -> ../../../../../../bus/usb/drivers/uvcvideo
```
and `ls -ld /sys/class/video4linux/video2/device/driver`:
```
lrwxrwxrwx 1 root root 0 Oct 31 21:52 /sys/class/video4linux/video2/device/driver -> ../../../../../../../../../../../../../../bus/usb/drivers/uvcvideo
```
So it looks like they're both using the uvcvideo driver. I've tried to remove and add the uvcvideo driver via: `modprobe -r uvcvideo && modprobe uvcvideo` with no luck.

**Some potential insight from `lsusb`:**

I ran the command `lsusb -t` with the following outputs:

 1. Upon bootup of my laptop:
```
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 10000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
    |__ Port 8: Dev 2, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 8: Dev 2, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 9: Dev 3, If 0, Class=Vendor Specific Class, Driver=, 12M
    |__ Port 10: Dev 4, If 0, Class=Wireless, Driver=btusb, 12M
    |__ Port 10: Dev 4, If 1, Class=Wireless, Driver=btusb, 12M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/2p, 12M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/2p, 12M
```
 2. After physically disconnecting my external display:
```
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 10000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
    |__ Port 8: Dev 2, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 8: Dev 2, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 9: Dev 3, If 0, Class=Vendor Specific Class, Driver=, 12M
    |__ Port 10: Dev 4, If 0, Class=Wireless, Driver=btusb, 12M
    |__ Port 10: Dev 4, If 1, Class=Wireless, Driver=btusb, 12M
```
 3. After physically reconnecting my external display:
```
/:  Bus 05.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/4p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/7p, 480M
        |__ Port 4: Dev 5, If 2, Class=Audio, Driver=snd-usb-audio, 12M
        |__ Port 4: Dev 5, If 0, Class=Audio, Driver=snd-usb-audio, 12M
        |__ Port 4: Dev 5, If 3, Class=Human Interface Device, Driver=usbhid, 12M
        |__ Port 4: Dev 5, If 1, Class=Audio, Driver=snd-usb-audio, 12M
        |__ Port 5: Dev 3, If 1, Class=Video, Driver=uvcvideo, 480M
        |__ Port 5: Dev 3, If 2, Class=Vendor Specific Class, Driver=, 480M
        |__ Port 5: Dev 3, If 0, Class=Video, Driver=uvcvideo, 480M
        |__ Port 7: Dev 4, If 0, Class=Human Interface Device, Driver=usbhid, 12M
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 10000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
    |__ Port 8: Dev 2, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 8: Dev 2, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 9: Dev 3, If 0, Class=Vendor Specific Class, Driver=, 12M
    |__ Port 10: Dev 4, If 0, Class=Wireless, Driver=btusb, 12M
    |__ Port 10: Dev 4, If 1, Class=Wireless, Driver=btusb, 12M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/2p, 12M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ohci-pci/2p, 12M
``` 

Thanks!

**Comment by patjak** [comment]
Sorry, this driver is only for the PCIe Facetime HD cameras. I have no insight in how the usb versions work.
