### ISSUE TITLE
Add suggestion to reboot in troubleshooting section?

### ISSUE THREAD

**Issue by hamishmb** [patjak/bcwc_pcie#240]
Hi there,

Thanks for the scripts and setup tools - works great for my Late 2013 Macbook Pro :)

/dev/video0 absolutely refused to appear for me until I rebooted the machine. This didn't happen the first time, only after a kernel upgrade - maybe worth adding to troubleshooting section?

**Comment by patjak** [comment]
Hi, thanks for the suggestion.

The wiki is open for anyone to edit. Feel free to add this information if you think it is helpful.

**Comment by hamishmb** [comment]
Okay, will do

**Comment by hamishmb** [comment]
All done :)

**Comment by patjak** [comment]
Great, thanks!
