### ISSUE TITLE
/dev/video not created (Ubuntu 15.04)

### ISSUE THREAD

**Issue by edsiper** [patjak/bcwc_pcie#29]
Ubuntu 15.04 + Kernel 4.3

My firmware:

```
4e1d11e205e5c55d128efa0029b268fe  /lib/firmware/facetimehd/firmware.bin
```

after loading the module there is no signs the /dev/videoX interface is created:

```
$ lsmod |grep facetime
facetimehd             94208  0
videobuf2_core         49152  1 facetimehd
videobuf2_dma_sg       16384  1 facetimehd
videodev              172032  3 v4l2_common,facetimehd,videobuf2_core

$ ls -l /dev/video*
ls: cannot access /dev/video*: No such file or directory
```

How can I debug what's happening with the module ?

**Comment by hobarrera** [comment]
Can you try running `modprobe -r bdc_pci` and then reinserting the module.

**Comment by edsiper** [comment]
:)

![facetimehd_working](https://cloud.githubusercontent.com/assets/369718/12008199/3705353c-abf1-11e5-9ced-6e4c108beb00.png)

**Comment by edsiper** [comment]
note: this is a MacBookPro11,1

**Comment by hobarrera** [comment]
For posterity's sake, this is documented [here](https://github.com/patjak/bcwc_pcie/wiki/Get-Started#additional-notes).

**Comment by Jancis** [comment]
Thank you @hobarrera for suggestion to add "modprobe -r bdc_pci"
Driver works on MacBookPro11,2

**Comment by begin29** [comment]
tried to do following actions for macbook 15, late 2016: 
```
# modprobe -r bdc_pci
# modprobe -r facetimehd
# modprobe facetimehd
```
/dev/video won't be created, and apps says "there no any video devices"

@WhyNotHugo any ideas?

**Comment by patjak** [comment]
@begin29 what does dmesg say?
