### ISSUE TITLE
Camera does not work in mplayer

### ISSUE THREAD

**Issue by hpe009** [patjak/bcwc_pcie#30]
Camera does not work in mplayer, I am only getting a black screen and a turned on camera but not myself @patjak Please help

**Comment by patjak** [comment]
Can you load the module with debugging and post the entire dmesg after the error has occured?
```insmod ./facetimehd.ko dyndbg==pmf```

**Comment by hpe009** [comment]
insmod: ERROR: could not load module ./facetimehd.ko: No such file or directory
PS: I am running ubuntu 15.10

**Comment by patjak** [comment]
You need to supply the path to the module. If you've installed the module you can try
```modprobe dyndbg==pmf```

**Comment by hpe009** [comment]
@patjak 
There is no error, the camera is on, but the mplayer windows is black with no video. Cheese webcamera player gives me a corrupted image but that is it.

**Comment by hpe009** [comment]
If you have teamviewer on your computer you can do those commands from your pc, do you have that?

**Comment by hpe009** [comment]
Getting this error from terminal while using mplayer:
[   vdpau] Error when calling vdp_video_surface_put_bits_y_cb_cr: VDP_STATUS_INVALID_Y_CB_CR_FORMAT
[VS] error (vdpVideoSurfacePutBitsYCbCr_glsl): not implemented source YCbCr format 'VDP_YCBCR_FORMAT_YUYV'

**Comment by hpe009** [comment]
@patjak It is working in skype though, but not in mplayer,cheese or in websites

**Comment by abustany** [comment]
@hpe009 use another "video output" for mplayer, for example "gl2": `mplayer -vo gl2 tv://`. Apparently some outputs cause mplayer to request a different pixel format for the input.

**Comment by hpe009** [comment]
@abustany Thanks this command worked: mplayer -vo gl3 tv://

@patjak please add this to the install instructions

**Comment by miekg** [comment]
Bumped into the same thing (sorry for adding noise to a closed issue). This was working in 14.04 (with upgraded 4.2 kernel), but is giving me this issue in ubuntu 16.04 (with kernel 4.3). 
(Yes I upgraded to 16.04 slightly before its release :-) )
