### ISSUE TITLE
Get the firmware without Mac OS Installed

### ISSUE THREAD

**Issue by jrock2004** [patjak/bcwc_pcie#31]
Ok, so I have not ran the mac os for the longest time on my Macbook Pro. Do I really need to reinstall El Capitan just to get this or is there another way to get the firmware? Thanks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[bcwc_pcie] Get the firmware withou..." ]
>Ok, so I have not ran the mac os for the longest time on my Macbook Pro Do I really need to reinstall El Capitan just to get this or is there another way to get the firmware? Thanks

There seem to be other ways (in the works). But yes, you'll need the driver
from El Captain. Note that upgrading made my system *not* boot Linux anymore.
Had to install refind to make that work again.

You can also try to email me privately ...

/Miek

--
Miek Gieben

**Comment by jrock2004** [comment]
Yep, the problem I have is Mac OS is no longer installed. HD way too small to support multiple OS

**Comment by hobarrera** [comment]
Give the code over at #27 a try, it should download the firmware for you (plus, more people testing it is a good thing).

**Comment by jrock2004** [comment]
I figured it out. Thanks
