### ISSUE TITLE
Flash not detecting camera

### ISSUE THREAD

**Issue by hpe009** [patjak/bcwc_pcie#33]
Title says it all

**Comment by wvengen** [comment]
Checking with Chromium, which says flash version 16.0.0.305 [here](https://www.adobe.com/software/flash/about/), I find the camera working. Make sure you have the latest version of bcwc_pcie.

**Comment by hpe009** [comment]
@wvengen I use Firefox and Flash version 20.0.0.267, says camera not detected

**Comment by hpe009** [comment]
I have found a fix for Firefox users and will post it to the wiki later.
