### ISSUE TITLE
Using camera after suspend makes the computer crash

### ISSUE THREAD

**Issue by hpe009** [patjak/bcwc_pcie#37]
On Ubuntu using camera after suspend freezes the computer

**Comment by edsiper** [comment]
I'd assume this it's an expected behavior, the power management routines are not yet implemented:

https://github.com/patjak/bcwc_pcie/blob/master/fthd_drv.c#L520

**Comment by hpe009** [comment]
@edsiper Anyway to go around this?

**Comment by edsiper** [comment]
do not suspend ? :)

**Comment by hobarrera** [comment]
Probably unloading the module before suspending should prevent this too.

**Comment by hpe009** [comment]
@hobarrera Can you tell me how to do that? I hav etried but I do not think I have done it right

**Comment by slashrsm** [comment]
````
modprobe -r facetimehd
````

**Comment by hpe009** [comment]
Any way I can put this in a script so that it launches the commands before sleep : modprobe -r facetimehd.
And on resume: modprobe -r bdc_pci and modprobe facetimehd?

**Comment by wvengen** [comment]
If you're on Ubuntu (and perhaps Debian), edit `/etc/default/acpi-support` and add `facetimehd` to its `MODULES` variable.

**Comment by hpe009** [comment]
Solution. DEV please add to install description:
Create this file: gksu gedit /lib/systemd/system-sleep/99facetimehd
And paste this and save:
#!/bin/sh
case $1/$2 in
  pre/*)
    echo "Going to $2..."
    modprobe -r facetimehd 
    ;;
  post/*)
    echo "Waking up from $2..."
    modprobe -r bdc_pci
    modprobe facetimehd
    modprobe bdc_pci
    ;;
esac

**Comment by patjak** [comment]
@hpe009 Thanks. Please add that to the wiki. The wiki is open for anyone to edit. Note that ```modprobe bdc_pci``` is not needed at post.

**Comment by hpe009** [comment]
@patjak Will do, added that line jsut in case.

**Comment by patjak** [comment]
@hpe009 Thanks

**Comment by derjohn** [comment]
@patjak 

For Ubuntu trusty we need:

/etc/pm/sleep.d/99_facetimehd

```
#!/bin/sh

case $1 in
    resume|thaw)
        logger -t pm 'Loading facetimehd kernel module'
        /sbin/modprobe facetimehd
        ;;
    suspend|hibernate)
        logger -t pm 'Removing facetimehd kernel module'
        /sbin/rmmod facetimehd
        exit 0
        ;;
esac
```

**Comment by wvengen** [comment]
For Ubuntu we can use existing acpi-support functionality https://github.com/patjak/bcwc_pcie/issues/37#issuecomment-167600296

**Comment by derjohn** [comment]
@wvengen I did try to do it via /etc/default/acpi-support - setting MODULES. Didn't work for me. I use Linux Mint 17, which is based on trusty.

**Comment by hpe009** [comment]
@wvengen That does not work I have tried.

**Comment by wvengen** [comment]
@hpe009 thanks for reporting back, strange.
btw, the driver unloads/loads itself now at suspend/resume since b5e3e74daafe67f371973e8484ac7492075701b6
