### ISSUE TITLE
Ubuntu Studio 15.10 on MacBook Air (Mid 2013) fails to work with Facetime HD driver

### ISSUE THREAD

**Issue by CoolGames** [patjak/bcwc_pcie#54]
## Built using make command on Ubuntu Studio 15.10

> lcpci -nnk
```
02:00.0 Multimedia controller [0480]: Broadcom Corporation 720p FaceTime HD Camera [14e4:1570]
	Subsystem: Broadcom Corporation 720p FaceTime HD Camera [14e4:1570]
	Kernel driver in use: bdc-pci
```

I just read that if it is not working at boot time then be sure to add facetimehd to /etc/modules !

Sorry to make an issue of it but maybe this will attract others searching for a solution online in 2016.

**Comment by CoolGames** [comment]
Solved [Spaces in Directory name](http://askubuntu.com/questions/367838/compiling-error-while-installing-realtek-rtl8111e-in-64-bit-13-10-config-x86-x].
Now extraction error
```
 $ ./extract-firmware.sh -x ../../AppleCameraInterface 


Error: Mismatching driver hash for ../../AppleCameraInterface
Error: The unknown hash is dfac86799c6cf0aceb59bb4e732be8f030e7943eb1146830c7136f62621c9853
Error: No firmware extracted!
```

**Comment by CoolGames** [comment]
Still not working even after trying [Additional Notes](https://github.com/patjak/bcwc_pcie/wiki/Get-Started#additional-notes).
I already have a /dev/video0 camera that responds to all the tests listed [here](https://github.com/patjak/bcwc_pcie/wiki/Get-Started#get-started-on-debian).

Previously working /dev/video0 no longer working with guvcview

**Comment by dcunited001** [comment]
@CoolGames for me, after i installed the `mtrack` touchpad drivers, then `facetimehd` does not autoload and instead bdc_pci does.

however, after i configured facetimehd in `/etc/modules`, i guess this blocks `bdc_pci` from loading. so now the webcam works on startup.

**Comment by patjak** [comment]
Added the "unload bdc_pci" info to the wiki.
