### ISSUE TITLE
Load module and test?

### ISSUE THREAD

**Issue by hemantborole** [patjak/bcwc_pcie#59]
Sorry , this isnt a issue per say, just my lack of understanding of modules in general.

I build the driver like so...
1. make
2. sudo make install

How do I test it? I tried modprobe facetimehd, modprobe bcwc_pcie but neither worked. How do I load the module?

**Comment by hobarrera** [comment]
Have you checked [the wiki](https://github.com/patjak/bcwc_pcie/wiki/Get-Started), including the additional notes section?
