### ISSUE TITLE
change default format and resolution

### ISSUE THREAD

**Issue by trackermb** [patjak/bcwc_pcie#66]
hi, is there a way to change the default format and resolution as video is grainy and very yellow this is what is shown in mplayer.
# 

Opening video decoder: [raw] RAW Uncompressed Video
Movie-Aspect is undefined - no prescaling applied.
VO: [xv] 640x480 => 640x480 Packed YUY2 
# Selected video codec: [rawyuy2] vfm: raw (RAW YUY2)

Thanks
Mark

**Comment by aanm** [comment]
See https://github.com/patjak/bcwc_pcie/issues/64 and https://github.com/patjak/bcwc_pcie/issues/52
