### ISSUE TITLE
driver not working on Ubuntu 16.04 with all updates

### ISSUE THREAD

**Issue by costastf** [patjak/bcwc_pcie#78]
After all the updates the driver fails to load with messages like:
modprobe: ERROR: ../libkmod/libkmod-module.c:977 command_do() Error running install command for facetimehd
modprobe: ERROR: could not insert 'facetimehd': Operation not permitted
 uname -r = 4.4.0-22-generic
sudo dmidecode -s system-product-name = MacBookPro12,1

Please let me know if there is any other information that you would need and i will provide it asap.

**Comment by cblaupanda** [comment]
try running modprode as root

```
modprobe: ERROR: could not insert 'facetimehd': Operation not permitted
```

**Comment by costastf** [comment]
Thanks, but I am running the command as root. This is the output I get 
by running it as root.

**Comment by costastf** [comment]
This was caused by an illegal modprobe script i had. Sorry.
