### ISSUE TITLE
Leave feedback to Broadcom?

### ISSUE THREAD

**Issue by Se6** [patjak/bcwc_pcie#8]
Hi,

Thanks for your work!

It might be helpful to put a link on the wiki to Broadcom feedback page: 
http://www.broadcom.com/contact/feedback.php
and ask people to leave a courteous request to provide any information to help develop a driver for the  the 1570 PCIe webcam used in MacBooks (mid 2013 and later), with a link to this repo.

Regards,

Seb

**Comment by kie27** [comment]
I have added a link in the wiki.

**Comment by patjak** [comment]
Thanks!
