### ISSUE TITLE
Broken with 4.8-rc3

### ISSUE THREAD

**Issue by xgnata** [patjak/bcwc_pcie#92]
The mainline is broken with 4.8-rc3 due to yet another ABI change of v4l2 / v2b.
Mainline inclusion would be cool ;)

make -C /lib/modules/4.8.0-040800rc3-generic/build M=/home/xavier/bcwc_pcie modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-040800rc3-generic'
  CC [M]  /home/xavier/bcwc_pcie/fthd_hw.o
  CC [M]  /home/xavier/bcwc_pcie/fthd_drv.o
  CC [M]  /home/xavier/bcwc_pcie/fthd_ringbuf.o
  CC [M]  /home/xavier/bcwc_pcie/fthd_isp.o
  CC [M]  /home/xavier/bcwc_pcie/fthd_v4l2.o
/home/xavier/bcwc_pcie/fthd_v4l2.c:296:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .queue_setup  = fthd_buffer_queue_setup,
                  ^
/home/xavier/bcwc_pcie/fthd_v4l2.c:296:18: note: (near initialization for ‘vb2_queue_ops.queue_setup’)
/home/xavier/bcwc_pcie/fthd_v4l2.c: In function ‘fthd_v4l2_register’:
/home/xavier/bcwc_pcie/fthd_v4l2.c:721:24: error: implicit declaration of function ‘vb2_dma_sg_init_ctx’ [-Werror=implicit-function-declaration]
  dev_priv->alloc_ctx = vb2_dma_sg_init_ctx(&dev_priv->pdev->dev);
                        ^
/home/xavier/bcwc_pcie/fthd_v4l2.c:721:22: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  dev_priv->alloc_ctx = vb2_dma_sg_init_ctx(&dev_priv->pdev->dev);
                      ^
/home/xavier/bcwc_pcie/fthd_v4l2.c: In function ‘fthd_v4l2_unregister’:
/home/xavier/bcwc_pcie/fthd_v4l2.c:761:2: error: implicit declaration of function ‘vb2_dma_sg_cleanup_ctx’ [-Werror=implicit-function-declaration]
  vb2_dma_sg_cleanup_ctx(dev_priv->alloc_ctx);
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:289: recipe for target '/home/xavier/bcwc_pcie/fthd_v4l2.o' failed
make[2]: *** [/home/xavier/bcwc_pcie/fthd_v4l2.o] Error 1
Makefile:1477: recipe for target '_module_/home/xavier/bcwc_pcie' failed
make[1]: *** [_module_/home/xavier/bcwc_pcie] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-040800rc3-generic'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by patjak** [comment]
Yea, looks like 	36c0f8b32c4bd4f668cedfba6d97afaa84f055fb broke it. It's a just a clean up patch so a trivial fix. Thanks for spotting. WIll close this when I've pushed the patch.

**Comment by graingert** [comment]
@patjak any status on this?

Thanks for your efforts!

**Comment by grahamc** [comment]
Confirming this issue on 4.8. @patjak do you have a patch ready?

**Comment by patjak** [comment]
Sorry for the delay, pushed a fix to mainline 887d0f531ef7b91457be519474136c3355c5132b
I'll probably not backport this to master so use mainline if you want to run on a recent kernel

**Comment by grahamc** [comment]
:+1: thank you!
